# Generated by Django 3.2.9 on 2021-11-29 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_lat', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('origin_lon', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('destination_lat', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('destination_lon', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InputLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_address', models.CharField(max_length=100)),
                ('origin_name', models.CharField(max_length=100)),
                ('destination_address', models.CharField(max_length=100)),
                ('destination_name', models.CharField(max_length=100)),
            ],
        ),
    ]
